name: Update Hugging Face repository
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.HF_SSH_PRIVATE_KEY }}
      - name: Push to Hugging Face
        run: |
          git remote set-url origin git@huggingface.co:spaces/fdaudens/voila-test.git
          git push origin main --force
