name: Update Hugging Face repository
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.HF_SSH_PRIVATE_KEY }}
      - name: Setup Git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa huggingface.co >> ~/.ssh/known_hosts
      - name: Push to Hugging Face
        run: git push git@huggingface.co:spaces/voila-dashboards/voila-huggingface main --force
