name: Update Hugging Face repository
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  push-to-hf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face
        env:
          HF_USER: ${{ secrets.HF_USER }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote set-url origin https://$HF_USER:$HF_TOKEN@huggingface.co/spaces/fdaudens/voila-test.git
          git push origin main --force
